name: Deploy to Ubuntu Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy
        run: |
          ssh -i ~/.ssh/github_actions deploy@${{ secrets.SSH_HOST }} "
            cd /var/www/window-wash-bot
            git pull origin main
            /usr/local/go/bin/go build -o telebot main.go
            sudo systemctl restart window-wash-bot
          "