name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Prepare server directory
        run: |
          ssh deploy@${{ secrets.SSH_HOST }} "
            rm -rf /var/www/window-wash-bot/*
            git clone --depth 1 https://github.com/${{ github.repository }}.git /var/www/window-wash-bot
            chown -R deploy:deploy /var/www/window-wash-bot
          "

      - name: Build and deploy
        run: |
          ssh deploy@${{ secrets.SSH_HOST }} "
            cd /var/www/window-wash-bot
            /usr/local/go/bin/go mod tidy
            if ! /usr/local/go/bin/go build -o telebot .; then
              echo 'Build failed!'
              exit 1
            fi
            sudo systemctl restart window-wash-bot
          "

      - name: Verify deployment
        run: |
          ssh deploy@${{ secrets.SSH_HOST }} "
            systemctl is-active window-wash-bot && 
            echo 'Service is running' || 
            (echo 'Service failed!'; journalctl -u window-wash-bot -n 20; exit 1)
          "